 
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'youtube_api_metrics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  youtube_api_metrics:
    +materialized: table
    staging:
      +tags: ["stage"]
      +materialized: view
    dimensions:
      +tags: ["dimension"]
      +materialized: table
    facts:
      +tags: ["fact"]
      +materialized: table
    bridge:
      +tags: ["bridge"]
      +materialized: table
    reports:
      +tags: ["report"]
      +materialized: table

# Version of the project file syntax
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['youtube_papi_metrics', 'dbt_utils']

# Ensure packages are included if using dbt-utils or others
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1  # or latest compatible version